-- This script 
-- ==> creates database users for the associates.
-- ==> creates roles assigned to the associates ; MANAGER, EMPLOYEE, HR_GENERALIST and HR_OPS

-- Start user and role creation for managers and Employees

USE ROLE securityadmin;

CREATE ROLE manager;
CREATE ROLE employee;

CREATE USER a7839 LOGIN_NAME='A7839' DISPLAY_NAME='KING'   PASSWORD='a7839' MUST_CHANGE_PASSWORD=FALSE;
CREATE USER a7698 LOGIN_NAME='A7698' DISPLAY_NAME='BLAKE'  PASSWORD='a7698' MUST_CHANGE_PASSWORD=FALSE;
CREATE USER a7782 LOGIN_NAME='A7782' DISPLAY_NAME='CLARK'  PASSWORD='a7782' MUST_CHANGE_PASSWORD=FALSE;
CREATE USER a7566 LOGIN_NAME='A7566' DISPLAY_NAME='JONES'  PASSWORD='a7566' MUST_CHANGE_PASSWORD=FALSE;
CREATE USER a7788 LOGIN_NAME='A7788' DISPLAY_NAME='SCOTT'  PASSWORD='a7788' MUST_CHANGE_PASSWORD=FALSE;
CREATE USER a7902 LOGIN_NAME='A7902' DISPLAY_NAME='FORD'   PASSWORD='a7902' MUST_CHANGE_PASSWORD=FALSE;
CREATE USER a7369 LOGIN_NAME='A7369' DISPLAY_NAME='SMITH'  PASSWORD='a7369' MUST_CHANGE_PASSWORD=FALSE;
CREATE USER a7499 LOGIN_NAME='A7499' DISPLAY_NAME='ALLEN'  PASSWORD='a7499' MUST_CHANGE_PASSWORD=FALSE;
CREATE USER a7521 LOGIN_NAME='A7521' DISPLAY_NAME='WARD'   PASSWORD='a7521' MUST_CHANGE_PASSWORD=FALSE;
CREATE USER a7654 LOGIN_NAME='A7654' DISPLAY_NAME='MARTIN' PASSWORD='a7654' MUST_CHANGE_PASSWORD=FALSE;
CREATE USER a7844 LOGIN_NAME='A7844' DISPLAY_NAME='TURNER' PASSWORD='a7844' MUST_CHANGE_PASSWORD=FALSE;
CREATE USER a7876 LOGIN_NAME='A7876' DISPLAY_NAME='ADAMS'  PASSWORD='a7876' MUST_CHANGE_PASSWORD=FALSE;
CREATE USER a7900 LOGIN_NAME='A7900' DISPLAY_NAME='JAMES'  PASSWORD='a7900' MUST_CHANGE_PASSWORD=FALSE;
CREATE USER a7934 LOGIN_NAME='A7934' DISPLAY_NAME='MILLER' PASSWORD='a7934' MUST_CHANGE_PASSWORD=FALSE;

ALTER USER a7698 SET DEFAULT_NAMESPACE = customer_db.cust_mdm DEFAULT_WAREHOUSE = compute_wh DEFAULT_ROLE = manager;
ALTER USER a7839 SET DEFAULT_NAMESPACE = customer_db.cust_mdm DEFAULT_WAREHOUSE = compute_wh DEFAULT_ROLE = manager;
ALTER USER a7782 SET DEFAULT_NAMESPACE = customer_db.cust_mdm DEFAULT_WAREHOUSE = compute_wh DEFAULT_ROLE = manager;
ALTER USER a7566 SET DEFAULT_NAMESPACE = customer_db.cust_mdm DEFAULT_WAREHOUSE = compute_wh DEFAULT_ROLE = manager;
ALTER USER a7788 SET DEFAULT_NAMESPACE = customer_db.cust_mdm DEFAULT_WAREHOUSE = compute_wh DEFAULT_ROLE = manager;
ALTER USER a7902 SET DEFAULT_NAMESPACE = customer_db.cust_mdm DEFAULT_WAREHOUSE = compute_wh DEFAULT_ROLE = manager;
ALTER USER a7499 SET DEFAULT_NAMESPACE = customer_db.cust_mdm DEFAULT_WAREHOUSE = compute_wh DEFAULT_ROLE = employee;
ALTER USER a7521 SET DEFAULT_NAMESPACE = customer_db.cust_mdm DEFAULT_WAREHOUSE = compute_wh DEFAULT_ROLE = employee;
ALTER USER a7654 SET DEFAULT_NAMESPACE = customer_db.cust_mdm DEFAULT_WAREHOUSE = compute_wh DEFAULT_ROLE = employee;
ALTER USER a7844 SET DEFAULT_NAMESPACE = customer_db.cust_mdm DEFAULT_WAREHOUSE = compute_wh DEFAULT_ROLE = employee;

GRANT ROLE MANAGER to user a7698;
GRANT ROLE MANAGER to user a7839;
GRANT ROLE MANAGER to user a7782;
GRANT ROLE MANAGER to user a7566;
GRANT ROLE MANAGER to user a7788;
GRANT ROLE MANAGER to user a7902;

GRANT ROLE EMPLOYEE TO USER a7499 ;
GRANT ROLE EMPLOYEE TO USER a7521 ;
GRANT ROLE EMPLOYEE TO USER a7654 ;
GRANT ROLE EMPLOYEE TO USER a7844 ;

-- End user and role creation for managers and employees

-- Start user and role creation for HR Generalist and HR Ops
-- Responsibilities of HR Generalist will have access to employees salary info and demographic details
-- Responsibilities of HR Ops will have access to employees id, name, email and location. They will NOT have access to salary.

CREATE ROLE HR_GENERALIST;
CREATE ROLE HR_OPS;

CREATE USER hrgen LOGIN_NAME='hrgen' DISPLAY_NAME='HR Generalist'  PASSWORD = 'hrgen' MUST_CHANGE_PASSWORD = FALSE 
DEFAULT_NAMESPACE = customer_db.cust_mdm DEFAULT_WAREHOUSE = compute_wh DEFAULT_ROLE = HR_GENERALIST;

CREATE USER hrops LOGIN_NAME='hrops' DISPLAY_NAME='HR Operations'  PASSWORD = 'hrops' MUST_CHANGE_PASSWORD = FALSE
DEFAULT_NAMESPACE = customer_db.cust_mdm DEFAULT_WAREHOUSE = compute_wh DEFAULT_ROLE = HR_OPS;

GRANT ROLE HR_GENERALIST TO USER hrgen ;
GRANT ROLE HR_OPS TO USER hrops ;

